# ArUco markeri - generirano pomocu collect_marker_poses.py
# DICT_4X4_50, velicina 0.2m
markers:
  - id: 1
    x: 11.709
    y: -0.978
    z: 0.35
    roll: 1.5708
    pitch: 0.0
    yaw: -3.1216

  - id: 5
    x: 11.062
    y: 5.15
    z: 0.35
    roll: 1.5708
    pitch: 0.0
    yaw: -1.5328

  - id: 10
    x: -0.52
    y: 4.849
    z: 0.35
    roll: 1.5708
    pitch: 0.0
    yaw: -0.5694

  - id: 15
    x: -10.493
    y: -2.062
    z: 0.35
    roll: 1.5708
    pitch: 0.0
    yaw: 1.612

  - id: 20
    x: -6.134
    y: 0.038
    z: 0.35
    roll: 1.5708
    pitch: 0.0
    yaw: 3.1052
